<?php

namespace Database\Seeders;

use App\Models\RolHabilidad;
use Illuminate\Database\Seeder;

class RolHabilidadesSeeder extends Seeder
{
    public function run(): void
    {
        $habilidades = [

            /* ════════════════════════════════════════════════════════════
             * FORMA 0 — Sin forma (habilidades universales básicas)
             * Accesibles para cualquier combatiente, sin requerir forma
             * específica. Coste y daño moderados, sin modificadores exagerados.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Golpe Simple',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 0,
                'efecto'       => 'Golpe directo sin técnica especial. Útil cuando la Fuerza escasea.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Guardia Básica',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 1,
                'efecto'       => 'Adopta una postura defensiva elemental que refuerza la capacidad de bloqueo.',
                'buff'         => ['defensa', 'defensa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Corte Veloz',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 2,
                'cooldown'     => 0,
                'efecto'       => 'Corte rápido que sacrifica potencia por velocidad de ejecución.',
                'buff'         => ['iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Disparo de Advertencia',
                'tipo'         => 'distancia',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 2,
                'cooldown'     => 1,
                'efecto'       => 'Proyectil de energía básico lanzado para presionar al rival sin comprometerse.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Empuje de Fuerza',
                'tipo'         => 'distancia',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 1,
                'cooldown'     => 1,
                'efecto'       => 'Onda telekinetica que desequilibra al rival, reduciendo su capacidad de reposicionarse.',
                'buff'         => null,
                'debuff'       => ['movimiento'],
            ],
            [
                'nombre'       => 'Concentración Táctica',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'self',
                'costo_fuerza' => 2,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Pausa breve para canalizar la Fuerza y agudizar los sentidos de combate.',
                'buff'         => ['ataque', 'punteria'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Golpe Desarmante',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 2,
                'cooldown'     => 2,
                'efecto'       => 'Golpe dirigido a la mano o muñeca del oponente para reducir su capacidad ofensiva.',
                'buff'         => null,
                'debuff'       => ['ataque', 'ataque'],
            ],
            [
                'nombre'       => 'Contraataque Instintivo',
                'tipo'         => 'melee',
                'forma'        => 0,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 2,
                'efecto'       => 'Respuesta inmediata al ataque enemigo, aprovechando su momento de sobreextensión.',
                'buff'         => ['defensa'],
                'debuff'       => null,
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 1 — Shii-Cho (La Vía del Sarlaac)
             * Primer estilo formal. Ataques amplios y barredores sin refinamiento.
             * Alta potencia, bajo control. Ideal para combate múltiple o contra armadura.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Barrido del Sarlaac',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 5,
                'cooldown'     => 1,
                'efecto'       => 'Corte horizontal amplio característico de Shii-Cho que abarca un arco extenso.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Corte Diagonal',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 0,
                'efecto'       => 'Tajo en diagonal descendente, el movimiento más básico de Shii-Cho bien ejecutado.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Embestida de Shii-Cho',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 6,
                'cooldown'     => 2,
                'efecto'       => 'Carga frontal con impulso corporal combinado, imposible de ignorar.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Finta Primitiva',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 1,
                'efecto'       => 'Movimiento engañoso que descoloca la reacción defensiva del oponente.',
                'buff'         => null,
                'debuff'       => ['iniciativa'],
            ],
            [
                'nombre'       => 'Golpe de Frente',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'Impacto frontal directo que busca romper la defensa a través de la fuerza bruta.',
                'buff'         => null,
                'debuff'       => ['defensa'],
            ],
            [
                'nombre'       => 'Guardia del Sarlaac',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Postura de bloqueo total en estrella; defiende múltiples ángulos simultáneamente.',
                'buff'         => ['defensa', 'defensa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Sobrecarga de Golpes',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 2,
                'efecto'       => 'Serie de impactos rápidos y toscos que saturan la defensa rival por volumen.',
                'buff'         => null,
                'debuff'       => ['defensa'],
            ],
            [
                'nombre'       => 'Ímpetu Salvaje',
                'tipo'         => 'melee',
                'forma'        => 1,
                'objetivo'     => 'target',
                'costo_fuerza' => 4,
                'damage'       => 7,
                'cooldown'     => 3,
                'efecto'       => 'Liberación total de fuerza física y de la Fuerza en un único ataque demoledor.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 2 — Makashi (La Vía del Ysalamiri)
             * Duelismo puro. Elegante, preciso y eficiente en costo de Fuerza.
             * Orientado a anular el ataque del rival y explotar aperturas.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Esocada de Precisión',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 0,
                'efecto'       => 'Estocada calculada que busca el punto de menor resistencia en la guardia rival.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Riposte Elegante',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 1,
                'damage'       => 3,
                'cooldown'     => 3,
                'efecto'       => 'Respuesta inmediata tras un bloqueo, convirtiendo la defensa en ataque con fluidez.',
                'buff'         => ['defensa', 'defensa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Velocidad del Ysalamiri',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'self',
                'costo_fuerza' => 1,
                'damage'       => 0,
                'cooldown'     => 5,
                'efecto'       => 'Microajuste de posición y ritmo que anticipa el siguiente movimiento rival.',
                'buff'         => ['iniciativa', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Corte de Muñeca',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 4,
                'efecto'       => 'Golpe quirúrgico a la extremidad armada que mina la potencia ofensiva del oponente.',
                'buff'         => null,
                'debuff'       => ['ataque', 'ataque'],
            ],
            [
                'nombre'       => 'Estocada Penetrante',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 5,
                'cooldown'     => 2,
                'efecto'       => 'Estocada directo a zona desprotegida, ejecutado tras identificar el patrón del rival.',
                'buff'         => null,
                'debuff'       => ['movimiento'],
            ],
            [
                'nombre'       => 'Danza del Duelo',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'self',
                'costo_fuerza' => 3,
                'damage'       => 0,
                'cooldown'     => 4,
                'efecto'       => 'Secuencia de pasos y fintas que eleva todos los aspectos del combate cuerpo a cuerpo.',
                'buff'         => ['ataque', 'defensa', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Precisión Absoluta',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 1,
                'damage'       => 4,
                'cooldown'     => 2,
                'efecto'       => 'Canaliza la Fuerza para guiar el sable al punto exacto donde el daño es máximo.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Golpe Decisivo de Makashi',
                'tipo'         => 'melee',
                'forma'        => 2,
                'objetivo'     => 'target',
                'costo_fuerza' => 4,
                'damage'       => 6,
                'cooldown'     => 6,
                'efecto'       => 'El ataque definitivo de la Forma II: una estocada única que colapsa defensa y moral.',
                'buff'         => null,
                'debuff'       => ['ataque', 'ataque', 'defensa'],
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 3 — Soresu (La Vía del Mynock)
             * Defensa suprema. Prioriza sobrevivir y agotar al rival.
             * Barely deals damage on its own; forces the opponent into mistakes.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Muro de Luz',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 3,
                'efecto'       => 'Barrera de bloqueos en cascada que cubre todos los ángulos de aproximación.',
                'buff'         => ['defensa', 'defensa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Deflexión Pasiva',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 0,
                'efecto'       => 'Bloqueo mínimo de energía que redirige el ataque sin desgaste propio.',
                'buff'         => ['movimiento'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Contraflexión',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 3,
                'efecto'       => 'Redirige la energía del ataque enemigo para devolverla como golpe débil.',
                'buff'         => ['ataque'],
                'debuff'       => ['ataque'],
            ],
            [
                'nombre'       => 'Resistencia del Mynock',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 2,
                'damage'       => 0,
                'cooldown'     => 4,
                'efecto'       => 'Trance de concentración que lleva la defensa física a un nivel casi imposible de romper.',
                'buff'         => ['defensa', 'defensa', 'movimiento', 'movimiento'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Espera Calculada',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Paciencia táctica que mejora la reacción e iniciativa sin exponer ningún flanco.',
                'buff'         => ['iniciativa', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Golpe desde la Defensa',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 3,
                'efecto'       => 'Ataque oportunista que no abandona la postura defensiva al ejecutarse.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Fortín de Soresu',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 3,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Combina escudo de la Fuerza con posición cerrada para ser casi indestructible un turno.',
                'buff'         => ['defensa', 'defensa', 'iniciativa', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Fortaleza Absoluta',
                'tipo'         => 'melee',
                'forma'        => 3,
                'objetivo'     => 'self',
                'costo_fuerza' => 4,
                'damage'       => 0,
                'cooldown'     => 3,
                'efecto'       => 'La máxima expresión de Soresu: convierte al usuario en un muro impenetrable durante un turno completo.',
                'buff'         => ['defensa', 'defensa', 'defensa', 'defensa', 'defensa'],
                'debuff'       => null,
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 4 — Ataru (La Vía del Halcón-Murciélago)
             * Acrobacia y velocidad extremas. Alta iniciativa y movimiento.
             * Agresivo y difícil de predecir, pero costoso en Fuerza.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Salto Acrobático',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 1,
                'damage'       => 5,
                'cooldown'     => 2,
                'efecto'       => 'Salto asistido por la Fuerza para atacar desde arriba, ganando ángulo y velocidad.',
                'buff'         => ['movimiento'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Torbellino de Ataru',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'Rotación veloz del cuerpo que desconcerta la capacidad de reacción del rival.',
                'buff'         => null,
                'debuff'       => ['iniciativa'],
            ],
            [
                'nombre'       => 'Velocidad del Halcón-Murciélago',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'self',
                'costo_fuerza' => 2,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Potencia la Fuerza en piernas y reflejos, volviéndose casi imposible de rastrear.',
                'buff'         => ['iniciativa', 'iniciativa', 'movimiento'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Doble Corte Volador',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 2,
                'efecto'       => 'Dos cortes ejecutados en distintas trayectorias durante un solo salto acrobático.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Lluvia de Golpes',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 3,
                'cooldown'     => 2,
                'efecto'       => 'Barrage de ataques rápidos desde distintos ángulos, colapsa la defensa por saturación.',
                'buff'         => null,
                'debuff'       => ['defensa', 'defensa'],
            ],
            [
                'nombre'       => 'Golpe Aéreo Devastador',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 6,
                'cooldown'     => 2,
                'efecto'       => 'Descenso en picado con toda la masa corporal y la Fuerza concentrados en un punto.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Fuga Acrobática',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 3,
                'efecto'       => 'Reposicionamiento acrobático que mejora velocidad y capacidad de anticipación.',
                'buff'         => ['movimiento', 'ataque', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Devastación Final de Ataru',
                'tipo'         => 'melee',
                'forma'        => 4,
                'objetivo'     => 'target',
                'costo_fuerza' => 5,
                'damage'       => 8,
                'cooldown'     => 3,
                'efecto'       => 'La culminación de Ataru: salto máximo seguido de impacto total, imparable en potencia.',
                'buff'         => ['ataque', 'movimiento'],
                'debuff'       => null,
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 5 — Shien / Djem So (La Vía del Dragón Krayt)
             * Fuerza pura y contraataque brutal. Alta capacidad ofensiva,
             * puede redirigir disparos y aplasta defensas con potencia física.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Tajo Descendente',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 5,
                'cooldown'     => 1,
                'efecto'       => 'Golpe vertical de arriba a abajo con toda la musculatura y la Fuerza detrás.',
                'buff'         => null,
                'debuff'       => ['defensa'],
            ],
            [
                'nombre'       => 'Deflexión Ofensiva',
                'tipo'         => 'distancia',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'Redirige un proyectil de Fuerza de vuelta al oponente con impulso adicional.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Potencia del Krayt',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 7,
                'cooldown'     => 2,
                'efecto'       => 'Golpe con la potencia máxima del cuerpo; quiebra defensas pasivas con facilidad.',
                'buff'         => null,
                'debuff'       => ['defensa', 'ataque'],
            ],
            [
                'nombre'       => 'Empuje de Fuerza Shien',
                'tipo'         => 'distancia',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 5,
                'cooldown'     => 2,
                'efecto'       => 'Onda de la Fuerza lanzada con potencia muscular que noquea y desorienta.',
                'buff'         => null,
                'debuff'       => ['movimiento', 'movimiento'],
            ],
            [
                'nombre'       => 'Postura del Dragón',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'self',
                'costo_fuerza' => 0,
                'damage'       => 0,
                'cooldown'     => 4,
                'efecto'       => 'Asume la posición de fuerza máxima del Dragón Krayt, combinando ataque y resistencia.',
                'buff'         => ['ataque', 'ataque', 'defensa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Explosión de Djem So',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 0,
                'damage'       => 6,
                'cooldown'     => 2,
                'efecto'       => 'Contraataque potenciado: absorbe el momentum del rival y lo devuelve multiplicado.',
                'buff'         => ['ataque', 'punteria'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Devastación del Dragón',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 7,
                'cooldown'     => 3,
                'efecto'       => 'Combo de dos golpes sucesivos que no da respiro; el segundo llega antes de que el rival se reponga.',
                'buff'         => null,
                'debuff'       => ['defensa', 'punteria', 'ataque'],
            ],
            [
                'nombre'       => 'Ira del Dragón Krayt',
                'tipo'         => 'melee',
                'forma'        => 5,
                'objetivo'     => 'target',
                'costo_fuerza' => 5,
                'damage'       => 9,
                'cooldown'     => 3,
                'efecto'       => 'El golpe definitivo de Djem So: concentra todo el poder del practicante en un único impacto devastador.',
                'buff'         => ['ataque', 'ataque', 'ataque'],
                'debuff'       => null,
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 6 — Niman (La Vía del Rancor)
             * Equilibrio entre el sable y los poderes de la Fuerza.
             * Versátil: melee y distancia, buffs balanceados, integración total.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Toque de la Fuerza',
                'tipo'         => 'distancia',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 3,
                'cooldown'     => 2,
                'efecto'       => 'Proyección sutil de la Fuerza que altera la guardia rival sin exponer al usuario.',
                'buff'         => null,
                'debuff'       => ['defensa'],
            ],
            [
                'nombre'       => 'Golpe Combinado',
                'tipo'         => 'melee',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'Ataque que sincroniza movimiento físico y empuje telekinetico en un solo acto.',
                'buff'         => null,
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Empuje-Corte de Niman',
                'tipo'         => 'melee',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'La Fuerza empuja al rival fuera de posición y el sable completa el corte antes de que reaccione.',
                'buff'         => null,
                'debuff'       => ['movimiento'],
            ],
            [
                'nombre'       => 'Sinfonía de la Fuerza',
                'tipo'         => 'melee',
                'forma'        => 6,
                'objetivo'     => 'self',
                'costo_fuerza' => 3,
                'damage'       => 0,
                'cooldown'     => 4,
                'efecto'       => 'Estado de flujo total entre cuerpo y Fuerza que eleva ataque, defensa y puntería simultáneamente.',
                'buff'         => ['ataque', 'defensa', 'punteria'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Telekinesis Ofensiva',
                'tipo'         => 'distancia',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 5,
                'cooldown'     => 2,
                'efecto'       => 'Lanza objetos del entorno contra el rival con precisión guiada por la Fuerza.',
                'buff'         => null,
                'debuff'       => ['defensa', 'movimiento'],
            ],
            [
                'nombre'       => 'Equilibrio del Rancor',
                'tipo'         => 'melee',
                'forma'        => 6,
                'objetivo'     => 'self',
                'costo_fuerza' => 2,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Restaura el equilibrio interno del combatiente, mejorando múltiples capacidades al mismo tiempo.',
                'buff'         => ['ataque', 'defensa', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Ráfaga Telekinetica',
                'tipo'         => 'distancia',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 4,
                'cooldown'     => 1,
                'efecto'       => 'Oleada de objetos levitantes que interrumpe el ritmo y la cadencia del oponente.',
                'buff'         => null,
                'debuff'       => ['iniciativa', 'iniciativa'],
            ],
            [
                'nombre'       => 'Convergencia de Niman',
                'tipo'         => 'melee',
                'forma'        => 6,
                'objetivo'     => 'target',
                'costo_fuerza' => 4,
                'damage'       => 6,
                'cooldown'     => 2,
                'efecto'       => 'Ataque final de Niman: el sable y la Fuerza actúan como uno, golpeando cuerpo y mente del rival.',
                'buff'         => ['ataque', 'defensa'],
                'debuff'       => ['defensa', 'movimiento'],
            ],

            /* ════════════════════════════════════════════════════════════
             * FORMA 7 — Juyo / Vaapad (La Vía del Vornskr)
             * Ferocidad pura, canaliza emociones como arma.
             * El mayor daño del sistema, costos elevados, cooldowns largos.
             * Algunos ataques mejoran al usuario en la misma medida que dañan al rival.
             * ════════════════════════════════════════════════════════════ */
            [
                'nombre'       => 'Frenesí de Juyo',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 2,
                'damage'       => 5,
                'cooldown'     => 1,
                'efecto'       => 'Ráfaga de golpes sin patrón predecible; la imprevisibilidad es la defensa y el ataque.',
                'buff'         => null,
                'debuff'       => ['defensa', 'defensa'],
            ],
            [
                'nombre'       => 'Emoción Canalizada',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'self',
                'costo_fuerza' => 3,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Convierte la ira o el miedo en pura potencia ofensiva durante el siguiente turno.',
                'buff'         => ['ataque', 'ataque', 'ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Embestida Vaapad',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 7,
                'cooldown'     => 2,
                'efecto'       => 'Carga feroz en la que el usuario se convierte en un proyectil de energía y sable.',
                'buff'         => ['ataque'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Torbellino del Vornskr',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 6,
                'cooldown'     => 2,
                'efecto'       => 'Espiral de cortes y giros que desorienta completamente al rival, rompiendo su concentración.',
                'buff'         => null,
                'debuff'       => ['iniciativa', 'defensa'],
            ],
            [
                'nombre'       => 'Circuito de Poder',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 3,
                'damage'       => 5,
                'cooldown'     => 1,
                'efecto'       => 'Absorbe la agresividad del rival y la devuelve amplificada; cuanto más agresivo él, más daño.',
                'buff'         => null,
                'debuff'       => ['ataque', 'iniciativa'],
            ],
            [
                'nombre'       => 'Desencadenamiento',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'self',
                'costo_fuerza' => 2,
                'damage'       => 0,
                'cooldown'     => 2,
                'efecto'       => 'Libera todos los limitadores internos; velocidad, instinto y potencia se disparan en cascada.',
                'buff'         => ['ataque', 'ataque', 'movimiento', 'iniciativa'],
                'debuff'       => null,
            ],
            [
                'nombre'       => 'Fuerza de la Ira',
                'tipo'         => 'distancia',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 4,
                'damage'       => 5,
                'cooldown'     => 2,
                'efecto'       => 'Proyecta la emoción negativa como onda de la Fuerza que mina cuerpo y voluntad del rival.',
                'buff'         => null,
                'debuff'       => ['ataque', 'defensa', 'movimiento'],
            ],
            [
                'nombre'       => 'Tormenta de Vaapad',
                'tipo'         => 'melee',
                'forma'        => 7,
                'objetivo'     => 'target',
                'costo_fuerza' => 6,
                'damage'       => 10,
                'cooldown'     => 3,
                'efecto'       => 'La habilidad más devastadora del catálogo: un huracán de golpes cargados con toda la emoción del combatiente. Solo para maestros de la Forma VII.',
                'buff'         => ['ataque', 'ataque', 'ataque'],
                'debuff'       => ['defensa', 'defensa', 'defensa'],
            ],
        ];

        foreach ($habilidades as $data) {
            RolHabilidad::firstOrCreate(
                ['nombre' => $data['nombre'], 'forma' => $data['forma']],
                $data
            );
        }

        $this->command->info('✓ ' . count($habilidades) . ' habilidades de rol insertadas (8 por cada Forma 0–7).');
    }
}
